/**
 * Shared NCI-first agent primer.
 *
 * - `buildNciFirstAgentPrimer()` returns the compact prompt body (used by benchmarks and the `nci-mcp` server).
 * - `buildNciFirstAgentPrimerReferenceDoc()` returns the longer SQLite/table reference used as a doc resource.
 *
 * The docs site syncs the reference doc to `apps/docs/nci-first-agent-primer.md` via
 * `pnpm --filter docs run sync:nci-first-agent-primer`.
 */

const NCI_FIRST_AGENT_PRIMER_COMPACT = [
  "You have access to the NCI CLI, which indexes TypeScript declarations from node_modules into SQLite for symbol discovery and relational joins — not a full typechecker.",
  'Subcommands: **query** (search/list) and **sql** (read-only SELECT). On Windows PowerShell use the call operator: **& "<path-to-nci.exe>" <subcommand> …args…**. **--max-rows** applies only to **nci sql**; for **query find** and **query evidence** cap hits with **-n / --limit** (defaults: 20 and 10).',
  "FAST PATH — run these two calls first, in order:",
  "1. **query active-package <packageName>** — resolves the installed **package_version**, confirms **indexed=true**, and returns **packageManager** for the directory NCI was invoked from. Pin the resolved **package_version** in all subsequent calls unless you are intentionally comparing versions.",
  "2. **query evidence --package <IndexedPackage> --package-version <V> [--source-package <NpmPackage>] --symbol <Anchor> [--symbol …] [--phrase <Text> …] [--kind <KindName>] [-n <N>] [--snippet-limit <M>]** — returns deduped symbol hits and batched signature/JSDoc snippets in one call, replacing chained **query symbol** + **query find** + **query snippet** workflows.",
  "Response shape: **data.symbols** holds deduped hits; **data.snippets** is an object keyed by **symbols.id** whose values are the stored **signature** / **js_doc** text — cite directly from there.",
  '**-n / --limit** (default 10) caps hit rows in **data.symbols**. **--snippet-limit** caps how many of those rows get a snippet in **data.snippets** (defaults to **--limit**). Use **query snippet "<id>"** as a standalone call when you need a snippet outside an evidence result.',
  "**--public-only** restricts **data.symbols** to rows where **symbols.is_internal = 0** (reachable on the package export surface). This is not the JSDoc **@public**/**@internal** tag, which lives in **symbols.visibility**.",
  "Accepted flags — only these, anything else exits non-zero: **--package** (required), **--package-version**, **--source-package**, **--symbol** (repeatable), **--phrase** (repeatable), **--kind** (case-sensitive AST kind_name: **InterfaceDeclaration**, **TypeAliasDeclaration**, **FunctionDeclaration**, **VariableStatement**, **MethodSignature**, **ExportDeclaration** — note **declare const …** rows are **VariableStatement** not **TypeAliasDeclaration**), **--public-only**, **-n / --limit**, **--snippet-limit**, **--database**, **--format** (plain|json|jsonl).",
  "**--kind** applies to every anchor in the call. Omit it if you are not certain every anchor shares the same **kind_name** — passing the wrong kind will return `0 hit(s); filter by **kindName** on the returned rows instead.",
  'Truncation: when the last element of **data.symbols** has **id**, **name**, and **kindName** all equal to **"<truncated>"**, raise **-n** or narrow with **--package-version** / **--source-package** / **--kind**.',
  "When **data.symbols** and **data.snippets** already contain what you need, stop. Do not probe further with **read_file**, **grep**, **glob**, or **sql**.",
  "NARROWING TOOLS — use when the fast path was insufficient:",
  "1. **query symbol <Name> --package <IndexedPackage> [--package-version] [--source-package <NpmPackage>] -n 10** — add **--source-package** to restrict to symbols whose declaration is owned by a specific npm package (**source_package_name**). Omit it when any match under the index is sufficient.",
  "2. **query find <phrase> --package <Indexed> [--source-package] [--kind <KindName>] [--package-version] -n 10** — scoped full-text search. If a dotted name returns nothing, retry with tokenized terms (Foo bar style).",
  "3. **query source-packages <IndexedPackage> <packageVersion>** — lists which source packages contribute declaration files under this index.",
  '4. **query show "<symbols.id>"** returns full row metadata including a trimmed signature preview — use it when you need column context. **query snippet "<symbols.id>"** returns the full **signature** + **js_doc** text — use it when you need cite-ready declaration text. Both take exactly one positional id. Ids suffixed **#2**, **#3**, … are separate graph rows; run **query overloads "<symbols.id>"** to get the full sibling set, then **snippet** each one.',
  "5. Path resolution — three layers: (1) which install wins (**package_dir** from active-package), (2) which package owns the declaration (**source_package_name**), (3) which file inside that install (**source_file_path**). Use **source_file_path** for disk navigation, not **file_path** when it contains index encoding. If **source_file_path** + install layout does not resolve to a real file, use **query snippet** / **query show** instead. Scope **glob**/**grep**/**read_file** only under one resolved concrete directory.",
  "6. After resolving a declaration directory, use actual filenames first. Fall back to **.d.mts** / **.d.ts** / **.d.cts** only on a miss.",
  "7. Use **read_file** / search only when **query show** / **query snippet** still lack what you need.",
  "8. A single well-scoped **SELECT** is appropriate for set-level work (name collisions, merge rows, dependency fan-out) when you already know the join and filters. Use **sql --schema** to inspect table structure first if unsure.",
  "9. Do not run **tsc -e** unless the task explicitly requires compile proof.",
  "SQL ANCHOR-SWEEP TEMPLATE:",
  "nci sql --format json --max-rows 40 -c \"SELECT s.id, s.name, s.kind_name, s.file_path, s.source_package_name FROM symbols s JOIN packages p ON p.package_id = s.package_id WHERE p.name = '<IndexedPackageName>' AND p.version = '<IndexedPackageVersion>' AND (LOWER(s.name) IN (<lowered_anchor_list>) OR s.name LIKE '%<OneAnchor>%') ORDER BY s.name LIMIT 40\"",
  "PATH ENCODING: **file_path** values containing **__nci_external__** or **__up__** are canonical index keys for SQLite — not filesystem paths to concatenate. For SQL joins and symbol id matching, use **file_path** as stored. For disk access, resolve via **source_package_name** + **source_file_path** + install layout. When that still does not yield a real file, use **query snippet** / **query show**.",
  "GRAPH SEMANTICS:",
  "Join packages to symbols via **symbols.package_id = packages.package_id**, filtered by **packages.name** and **packages.version**.",
  "**symbols.symbol_id** (integer) is for SQL joins to dependency tables. **symbols.id** (string) is the stable handle for **query snippet**; **symbol_dependencies.to_symbol_id_text** references this form.",
  '**symbol_dependencies** holds resolved "uses" edges. **symbol_surface_dependencies** holds rolled-up namespace/module surface deps — the two are not interchangeable on arbitrary member rows.',
  "**parent_symbol_id** is immediate lexical containment. **enclosing_module_declaration_id** is the surrounding ModuleDeclaration / namespace block — not a type-use edge and not always the same as **parent_symbol_id**.",
  "Id suffixes **#2**, **#3**, … disambiguate homonyms — compare the full **id**, not just **name**.",
  "**file_path** is the primary declaration site. **symbol_additional_files** lists other declaration files merged into the same symbol row.",
  "**entry_visibility_json** lists package-relative entry/barrel paths through which this symbol is reachable on the public export surface — distinct from **file_path** (the definition site) and **symbol_additional_files** (merge sites).",
  "**merge_provenance_json** describes how a row was merged: **merge_scope** (same merge-key collision), **identical_fold** (same name/kind/signature across external files), or **overload_key**. Pair with **signature** and **kind_name** when distinguishing overloads from re-exports.",
  "**is_internal = 1** means the symbol is not on the public export path from package entries. **is_inherited** means the member is synthesized via inheritance; see **symbol_inherited_from_sources** for the contributing base symbol ids.",
  "Run **sql --schema** for the full DDL.",
].join("\n");

const NCI_FIRST_AGENT_PRIMER_LIVE = [
  "You have access to the NCI CLI. NCI indexes TypeScript declarations from `node_modules` into **SQLite** — symbol discovery and relational joins, not a full typechecker.",
  "",
  '**Subcommands:** `query` (search/list) and `sql` (read-only `SELECT`). Windows PowerShell: **`& "<path-to-nci.exe>" <subcommand> …args…`** (call operator). **`--max-rows`** applies **only** to `nci sql`. For `query find` and `query evidence`, cap hits with **`-n` / `--limit`** (defaults: 20 and 10).',
  "",
  "**Fast path — preferred first two NCI calls (in order):**",
  "1. **`query active-package <packageName>`** — resolve the project's installed `package_version` and confirm `indexed=true`. JSON includes **`packageManager`** for **the directory NCI was invoked from** (the project context resolved at call time). Use the resolved `package_version` to pin step 2 (and any later `query symbol` / `query find`) unless you intentionally compare versions, or only one indexed version exists for this name.",
  '2. **`query evidence --package <IndexedPackage> --package-version <V> [--source-package <NpmPackage>] --symbol <Anchor> [--symbol …] [--phrase <Text> …] [--kind <KindName>] [-n <N>] [--snippet-limit <M>]`** — bundled exact-name hits + FTS phrase hits + **batched** signature/JSDoc snippets in **one** CLI invocation. Replaces chained `query symbol` + `query find` + per-id `query snippet` calls for the common "find these symbols and cite them" task.',
  '- **Evidence response shape:** the JSON envelope carries `data.symbols` (deduped hits, see truncation marker below) and `data.snippets` — a JSON **object keyed by `symbols.id`** whose values hold the same stored `signature` / `js_doc` text that `query snippet "<id>"` reads. `data.snippets[id]` is cite-ready content for any id present.',
  "- **`-n` / `--limit` vs `--snippet-limit`:** `-n` (a.k.a. `--limit`, default `10`) caps how many **hit rows** appear in `data.symbols` after dedupe across all `--symbol` / `--phrase` anchors. `--snippet-limit <M>` caps how many of those returned hits get a **snippet** attached in `data.snippets` (default = `--limit`, i.e. 1:1 coverage). Lower `--snippet-limit` only when you explicitly want hit rows without paying for every snippet body; raising `-n` widens both unless you also pass `--snippet-limit`. `query evidence` is the **batched, single-process** path for many snippets in one call; `query snippet` is a separate subcommand that takes **one positional `<id>`** (no other arguments) and is appropriate when you need a snippet outside of an evidence packet.",
  "- **`--public-only`:** restricts `data.symbols` to rows where `symbols.is_internal = 0` — i.e. reachable on the **package export surface** from `types` / `exports` entry resolution. This is **not** the JSDoc `@public` / `@internal` tag (that lives separately in `symbols.visibility`). Use it to hide symbols that were crawled but are not exported from the package's public API; omit it if internal supporting types are still needed.",
  "- **`query evidence` accepted flags (exhaustive — anything else fails clap parsing, do not invent flags):** `--package <NAME>` (required, indexed package name), `--package-version <VERSION>`, `--source-package <NAME>` (filter by owning npm package of the declaration), `--symbol <NAME>` (repeatable, exact name lookup), `--phrase <TEXT>` (repeatable, FTS phrase fallback), `--kind <KIND>` (literal `kind_name` such as `InterfaceDeclaration` / `TypeAliasDeclaration` / `FunctionDeclaration` / `VariableStatement` / `MethodSignature` / `ExportDeclaration` — case-sensitive AST node names; `declare const … = …` rows are `VariableStatement`, **not** `TypeAliasDeclaration`), `--public-only`, `-n` / `--limit <N>` (default `10`), `--snippet-limit <N>` (default `--limit`); plus the global query options `--database <PATH>` and `--format <plain|json|jsonl>`. Any other flag is invalid and will exit non-zero before any DB work.",
  "- **Choosing `--kind` correctly:** `--kind` is applied to **all** anchors in the same `evidence` call (exact `--symbol` and FTS `--phrase` alike). If you do not know the precise `kind_name` of every target, **omit `--kind`** — passing the wrong kind will return `0 hit(s), empty anchors` even when the symbols exist. Use `--kind` only when every anchor genuinely shares one literal `kind_name`; otherwise filter post-hoc by reading `kindName` on the returned hits.",
  "- **Stop condition:** if `data.symbols` already contains the symbol(s) you need and `data.snippets` already carry the signature/JSDoc to cite, **stop discovery**. Do not re-confirm exact NCI evidence with `read_file` / `grep` / `glob` / broader SQL / shell probes.",
  '- **Truncation marker (no new envelope key):** when the trailing element of `data.symbols` has `id`, `name`, AND `kindName` all equal to the literal string `"<truncated>"`, more results existed than `--limit` allowed. Either raise `-n` / `--limit`, narrow with `--package-version` / `--source-package` / `--kind`, or pick a more specific anchor — do **not** switch to `read` / `grep` to compensate. Real symbol rows never use that sentinel.',
  "- The numbered narrowing-tools list below is the **fallback** when steps 1–2 were insufficient (no version resolved, anchors unknown, sentinel says truncated, or you need overload siblings / overload-key inspection).",
  "",
  "**Narrowing tools (fallback / when fast path was insufficient):**",
  "1. **`query symbol <Name> --package <IndexedPackage> [--package-version] [--source-package <NpmPackage>] -n 10`** — add **`--source-package`** to restrict rows to symbols whose **owning declaration** is that npm package (matches `source_package_name`: the package that **authored** the `.d.ts`, e.g. a type living in a dependency while the **indexed** package is the app). Omit it when any matching symbol under the index is enough.",
  "2. **`query find <phrase> --package <Indexed> [--source-package] [--kind <KindName>] [--package-version] -n 10`** — scoped FTS; if a dotted name returns nothing, retry with tokenized terms (`Foo bar` style).",
  "3. **`query source-packages <IndexedPackage> <packageVersion>`** — list which source packages contribute declaration files under this index (fast dependency-surface check).",
  '4. **Detail on a row — `query show` vs `query snippet`:** **`query show "<symbols.id>"`** returns the **full row metadata** (name, `kind_name`, `file_path`, `source_package_name`, `source_file_path`, plus a **trimmed `signature` preview**, etc.) — use it when you need column context, not just text. **`query snippet "<symbols.id>"`** returns only the **full stored `signature` + `js_doc`** text (no row metadata, no preview trimming) — use it for cite-ready declaration text once you already have the id. Both take exactly one positional `<id>` and no flags. String ids with **`#2` / `#3`** are separate graph rows; run **`query overloads "<symbols.id>"`** once to get the full sibling set (same `package_id` + `name` + `parent_symbol_id`), then `snippet` each before treating them as the same API.',
  "5. **NodeModules path-first contract (paired rules):** **`package_dir`** from `query active-package` is the **indexed** npm package install root only. Each symbol row carries **`symbols.file_path`** (primary declaration path in the DB), **`source_package_name`**, and **`source_file_path`** (path inside the owning package; **`source_file_path` is NOT NULL in SQLite**—never literally missing as SQL NULL). Think in three layers: (1) which install wins (**`package_dir`** / active-package), (2) which package owns the declaration (**`source_package_name`**), (3) which file inside that install — for **disk** navigation use **`source_file_path`** (and resolved install roots), not raw **`file_path`** when it uses index encoding (see Path encoding below). If **`source_file_path` + install layout still does not yield a file on disk**, treat it as “unusable for disk” and use **`query snippet`** / **`query show`** instead of guessing paths. Map to **one concrete disk directory** (virtual store, hoisted `node_modules`, etc.), then scope `glob`/`grep`/`read_file` **only under that directory**. Do not run ignore-aware `glob`/`grep` over broad `node_modules` trees for discovery; never start with `**/node_modules/**`.",
  "6. **Extension handling (paired with step 5):** after resolving a concrete declaration directory, inspect that directory once and use actual filenames first. Use `*.d.mts` / `*.d.ts` / `*.d.cts` only as fallback refinement on miss, not as mandatory multi-pass probing.",
  "7. **Repo file tools** (`read_file` / search) only when `query show` / `query snippet` still lack what the task needs.",
  "8. **Read-only `sql`:** a **single** well-scoped `SELECT` (see template) is appropriate for set-level work—name collisions, merge rows, dependency fan-out—**when you already know the join and filters**. If table/column names or keys are still fuzzy, use **`sql --schema`** and/or `query` to narrow first; speculative SQL (wide joins, wrong `package_id`) wastes steps the same way repeated blind `query find` does. Match the tool to how sure you are, not a rule that always prefers or avoids SQL.",
  "9. **Compilation:** do not run ad-hoc `tsc -e` unless the task explicitly requires compile proof; prefer `query` / `snippet` / `sql` declaration evidence.",
  "",
  "**One SQL anchor-sweep template** (replace placeholders; keep read-only; use `--max-rows`):",
  "`nci sql --format json -c \"SELECT s.id, s.name, s.kind_name, s.file_path, s.source_package_name FROM symbols s JOIN packages p ON p.package_id = s.package_id WHERE p.name = '<IndexedPackageName>' AND p.version = '<IndexedPackageVersion>' AND (LOWER(s.name) IN (<lowered_anchor_list>) OR s.name LIKE '%<OneAnchor>%') ORDER BY s.name LIMIT 40\"`",
  "",
  "**Path encoding (`symbols.file_path` and `__nci_external__`):** when a declaration sits outside the indexed package root, **`file_path`** can contain `__nci_external__` / `__up__` segments. Those tokens are **canonical index keys for SQLite and `query` ids** — they mean “outside the package” in the graph, **not** a folder path you should concatenate with the repo root and then `glob` or `cd`. **For SQL joins, filtering, and matching symbol ids, treat `file_path` as stored.** **For opening files on disk, do not navigate by splitting `file_path`/`__nci_external__`:** use **`source_package_name` + `source_file_path`** together with **`package_dir`** / install layout to reach the real package directory, then list or read there. **`source_file_path`** is **NOT NULL** in DDL; “absent” in practice means you still cannot resolve a real file—fall back to **`query snippet`** / **`query show`**. Prefer **`query snippet`** whenever you need declaration text without a reliable disk path.",
  "",
  "**Graph semantics (read this before interpreting `--schema` rows):**",
  "- **Join packages to symbols:** `symbols.package_id = packages.package_id`; filter by `packages.name` and `packages.version` for the indexed install.",
  "- **`symbols.symbol_id` (integer)** — use for SQL joins to dependency tables. **`symbols.id` (string)** — stable symbol handle for `query snippet`; **`symbol_dependencies.to_symbol_id_text`** targets this string form.",
  '- **`symbol_dependencies`** — resolved **"uses"** edges (what this declaration references). **`symbol_surface_dependencies`** — rolled-up namespace/module surface deps; **do not** treat as interchangeable with **`symbol_dependencies`** on an arbitrary member row.',
  "- **`parent_symbol_id`** — immediate **lexical containment** (e.g. member under class). **`enclosing_module_declaration_id`** — which **`ModuleDeclaration` / namespace block** encloses the symbol (surrounding module shape); **not** a type-use edge and **not** always the same relationship as `parent_symbol_id`.",
  "- **`id` suffixes `#2`, `#3`, …** — disambiguate homonyms; compare full **`id`**, not just `name`.",
  "- **`file_path`** — primary declaration site (package-relative). **`symbol_additional_files`** — **other** declaration files that contributed to **this same merged** symbol row (multi-site merge); non-empty means multiple physical declaration locations.",
  "- **`entry_visibility_json`** — JSON list of package-relative **entry / barrel** paths through which this symbol is reachable on the **public export surface** (`types` / `exports` traversal). **≠** `file_path` (definition may be internal file while export is via index). **≠** `symbol_additional_files` (those are merge sites, not “which export path surfaced the name”).",
  "- **`merge_provenance_json`** — when present, describes **how** this row was merged; typical **`kinds`** values: **`merge_scope`** (same merge-key collision), **`identical_fold`** (same name/kind/normalized signature across external files folded into one row), **`overload_key`** (overload-style keys). Pair with **`signature`** / **`kind_name`** when interpreting overloads vs re-exports.",
  "- **`is_internal`** — export-graph reachability (**`1`** = not on public export path from package entries), **not** “skip this row.” **`is_inherited`** — synthesized inherited member; see **`symbol_inherited_from_sources`** for contributing base symbol ids.",
  "",
  "Authoritative column list: run `sql --schema` on the NCI binary when you need exact DDL.",
].join("\n");

/** Longer reference doc (SQLite tables, example joins). Synced into `apps/docs/nci-first-agent-primer.md`. */
const NCI_FIRST_AGENT_PRIMER_REFERENCE_DOC = [
  "You have access to the NCI CLI. NCI crawls TypeScript declaration files in `node_modules` and stores a **graph of symbols** in **SQLite**: one database file, read-only from your perspective. The point is fast **symbol discovery** (what exists, where, what it references) and **relational checks** (joins across packages, dependencies, merge metadata)—not a full TypeScript typechecker. The CLI gives you:",
  "- **`query`** — text search / listing over the indexed symbol set (convenient for names and paths).",
  "- **`sql`** — the same data as relations: `SELECT` over `packages`, `symbols`, and the `symbol_*` tables.",
  '- **Shell invocation (Windows PowerShell):** Always run the binary as **`& "<path-to-nci.exe>" <subcommand> …args…`** (call operator). A quoted path immediately followed by a bare token like `sql` or `query` is **not** parsed as a subcommand—the shell treats the quoted string as a value, then errors on the next word.',
  "- **Row caps:** **`--max-rows`** applies **only** to **`nci sql`**. For **`nci query find <phrase>`**, cap how many hits are returned with **`-n` / `--limit`** (default **20**). **`--max-rows` is not valid on `query find`**; use `sql` when you need that cap.",
  "",
  "**Fast path for declaration evidence:**",
  "1. Start with exact symbols when you know the API name:",
  "   - Resolve active installed package context first when multiple versions may exist in the DB:",
  "   - `query active-package <IndexedPackageName>`",
  '   - "example": `query active-package <IndexedPackageName>`',
  "   - JSON output includes **`packageManager`** (hint from root `package.json` **`packageManager`** or lockfiles).",
  "   - With **`index_root_workspace: false`** and non-empty **`workspaces`** in `nci.config.json`, repo-root **`node_modules`** is excluded from active-package candidate roots (config only for `query`; not overridden by `nci index --skip-root-workspace`).",
  "   - Use the selected `package_version` from active-package output to pin downstream `query symbol` / `query find` calls unless intentionally comparing versions.",
  "   - `query symbol <ExactSymbolName> --package <IndexedPackageName> -n 10`",
  '   - "example": `query symbol Client --package <IndexedPackageName> -n 10`',
  "   - `query symbol <ExactSymbolName> --package <IndexedPackageName> --source-package <SourcePackageName> -n 10`",
  '   - "example": `query symbol Client --package <IndexedPackageName> --source-package <SourcePackageName> -n 10`',
  "   - Add `--package-version <IndexedPackageVersion>` when multiple versions of the indexed package exist in the DB.",
  '   - "example": `query symbol Client --package <IndexedPackageName> --package-version <IndexedPackageVersion> -n 10`',
  "2. Use scoped FTS for discovery:",
  "   - `query find <SearchPhrase> --package <IndexedPackageName> --source-package <SourcePackageName> -n 10`",
  '   - "example": `query find timeout --package <IndexedPackageName> --source-package <SourcePackageName> -n 10`',
  "   - `query find <SearchPhrase> --package <IndexedPackageName> --kind <KindName> -n 10`",
  '   - "example": `query find timeout --package <IndexedPackageName> --kind FunctionDeclaration -n 10`',
  "   - If your phrase contains punctuation (for example `Output.apply`), retry with tokenized terms (`Output apply`) when needed.",
  '   - "example": `query find Result map --package <IndexedPackageName> --source-package <SourcePackageName> -n 10`',
  "   - Add `--package-version <IndexedPackageVersion>` for deterministic version-scoped results.",
  '   - "example": `query find timeout --package <IndexedPackageName> --package-version <IndexedPackageVersion> -n 10`',
  "   - Discover available source packages quickly with `query source-packages <IndexedPackageName> <IndexedPackageVersion>`.",
  '   - "example": `query source-packages <IndexedPackageName> <IndexedPackageVersion>`',
  "3. Use the returned `id` as the handle for cite-ready detail:",
  '   - `query show "<symbol-id>"`',
  '   - "example": `query show "<symbol-id-from-query-find-or-symbol>"`',
  '   - `query snippet "<symbol-id>"`',
  '   - "example": `query snippet "<symbol-id-from-query-find-or-symbol>"`',
  '   - "example": if you see ids like `...::Client#2` / `...::Client#3`, treat each `#` id as a distinct disambiguated symbol row (not overload-only) and run `query snippet` on each id before concluding equivalence.',
  "   - `query snippet` accepts a **single positional `<symbol-id>`** (no flags). For many snippets in one CLI process, use `query evidence` — the JSON envelope returns `data.snippets` as an object keyed by `symbols.id`, and `--snippet-limit` defaults to `--limit`.",
  "4. Use file tools only after `query show` / `query snippet` lacks the declaration text needed for the final answer. `query` search/show rows carry a signature preview (currently capped), while `query snippet` returns stored full signature/JSDoc text from SQLite for the selected symbol id.",
  '5. Avoid ad-hoc compile probes unless the task explicitly requires compilation evidence. "example": do not run `tsc -e`; rely on `query`/`snippet` declaration evidence first.',
  "",
  "**After confirmation, widen with SQL (only when needed):** Once you confirm the right symbol/package via `query`, use `sql` for broader relational checks (same-name collisions, cross-version comparisons, dependency fan-in/out, inheritance/source provenance). Keep `query` for fast narrowing and use `sql` only for wider-scope architectural/evidence checks where set-level joins matter.",
  "- Example: after confirming `Output` in one package version, run SQL scoped by package + version + source package to inspect sibling rows and avoid false assumptions from a single hit.",
  "",
  "**Authoritative column list:** run `sql --schema` on the NCI binary. If anything below disagrees with that DDL, **believe the schema**.",
  "",
  "**Package-relative path encoding (`__nci_external__`, `__up__`):** When a declaration resolves **outside** the indexed package root, stored paths do **not** use raw `../` segments. The index uses a **canonical encoding**: each parent hop outside the package root adds **`__nci_external__`** plus one **`__up__`** segment (repeat for multiple hops). Example shape: `__nci_external__/__up__/other/x.d.ts`. That encoded string is for **stable SQLite keys and joins**, not a literal directory tree to walk under `node_modules`. **`symbols.file_path`** and internal symbol **`id`** values (`pkg@version::file_path::name`) may contain these tokens. For package/file ownership semantics, use **`source_package_name`** + **`source_file_path`** (and `source_package_version` when non-null) instead of reverse-parsing encoded folders. Prefer entry/public surfaces (`types`/`exports`, **`entry_visibility_json`** when present) and relational lookups over reconstructing disk paths from `../../` heuristics or by splitting `id` on `::` alone.",
  "",
  "---",
  "",
  "**Table `packages`:** `package_id`, `name`, `version`, index stats, timestamps. To filter symbols by package, use `symbols.package_id = packages.package_id` and `packages.name` / `packages.version`.",
  "",
  "**Table `symbols` (one row per **graph symbol** after the merge phase):**",
  "- **`symbol_id`:** integer row id.",
  "- **`package_id`:** which package this symbol belongs to.",
  "- **`id`:** stable string id (scoped to the indexed package version). Use this when joining to dependency tables or comparing to `to_symbol_id_text`.",
  "  - **`#` suffixes (`#2`, `#3`, …):** **Disambiguation**, not overload indices by themselves. The graph assigns **unique** ids when the same human-readable name would otherwise collide:",
  "    - **Exported symbols (`is_internal = 0`):** the **first** row for a given short `name` in the package typically uses `pkg@version::name`. **Further homonyms** (same exported `name`, different declarations) become `pkg@version::name#2`, `#3`, … in stable crawl order.",
  "    - **Internal symbols (`is_internal = 1`):** ids are usually **`pkg@version::file_path::name`**. If the **same file + same name** still produces multiple distinct symbols (e.g. overload rows that stay separate), the **second and later** occurrences add **`#2`, `#3`** on that **file-qualified** base (`…::file.d.ts::sym#2`).",
  "  - **If two SQL rows share the same base name but different `#n`:** they are **different symbol rows** by construction—compare full **`id`** strings, not only `name`. Do **not** assume `#2` always means “second overload” globally; it means “second disambiguated occurrence” in that package/file context.",
  "- **`name`:** the symbol’s short name; nested members may still use dotted segments in `name`—**do not infer the lexical parent only from string parsing** when `parent_symbol_id` is set.",
  "- **`kind`:** numeric internal code; **`kind_name`:** string form of the declaration kind (e.g. `FunctionDeclaration`, `InterfaceDeclaration`, `MethodSignature`, `ExportDeclaration`). Use `kind_name` with `name` and `signature` to tell functions from types from re-exports.",
  "- **`file_path`:** path to the **primary declaration site** for this graph row—package-relative. Merge may fold other sites into the same row; those extra physical files are recorded in **`symbol_additional_files`**, not by repeating them as extra `file_path` columns.",
  "- **`source_package_name`:** npm package that owns the declaration (`packages.name` for in-tree symbols; dependency package id parsed from the first `node_modules/<pkg>/` segment for `__nci_external__` paths). This is the canonical field for `--source-package` filters.",
  "- **`source_package_version`:** semver of the source package **only** when the source package is the indexed package. For external dependency declarations this is usually **NULL** by design; folder names like `@scope+pkg@x.y.z` are install-layout artifacts and are not treated as authoritative source semver.",
  "- **`source_file_path`:** path relative to `source_package_name` (mirrors `file_path` for in-package symbols; dependency-local path for external symbols). DDL stores it **NOT NULL**; use this when citing where the declaration lives inside the owning package. If disk navigation still fails, use **`query snippet`** rather than guessing.",
  "- **`entry_visibility_json` (TEXT, optional):** JSON array text of package-relative paths—**which package entry / barrel files make this symbol reachable on the public export surface** (`types` / `exports` roots and re-export traversal). This is the persisted SQL form of entry-surface visibility metadata. Populated when the symbol’s file (or the file resolved from package entry re-export) is one of the indexed **entry files**. **Not** the same as **`file_path`**: a symbol may be **defined** in `dist/foo.d.ts` but **reachable** only via `dist/index.d.ts`—then `file_path` is `foo`, while **`entry_visibility_json`** lists index/barrel paths that surface it. **Not** the same as **`symbol_additional_files`**: those are **extra declaration merge sites** for the same merged symbol, not “which entry re-exported this name.” If the only entry path equals **`file_path`** alone, the engine often omits the field as redundant—**NULL / absent** does not mean “not exported”; use **`is_internal`** plus this column when present.",
  "- **`signature`:** declaration signature / export text. **After merge,** the engine may **fuse** several normalized-distinct signature bodies into one field (newline-separated blocks), not “first file only.” If two overloads collapse when their normalized signatures match, you will not see duplicate raw text for the same normalized overload key.",
  "- **`js_doc`:** JSDoc when present.",
  "- **`parent_symbol_id`:** the **lexical / containment** parent for member shapes (e.g. a method’s parent class or interface id). This answers “this member lives under which container in the graph.” It is **not** a “this type uses that type” edge. For **use** relationships, use **`symbol_dependencies`** (or the graph’s `dependencies` when not using SQL). **Never** replace dependency reasoning with `parent_symbol_id` or vice versa.",
  "- **`enclosing_module_declaration_id`:** string id of the **enclosing module / namespace declaration** row (`ModuleDeclaration`-like container) for module-scoped symbols—**which module block** this symbol belongs to. **Not** a type-reference edge and **not** the same as `parent_symbol_id` for every kind (parent is often the immediate lexical owner; enclosing module is the surrounding module/namespace declaration id). Use it when you need “inside which module namespace” vs following **`symbol_dependencies`** for references.",
  "- **`merge_provenance_json`:** present when this row **absorbed more than one** declaration. JSON object; typically a `kinds` array whose values describe **how** the row was formed (snake_case labels), for example:",
  "  - **`merge_scope`:** at least one contribution came from the same **declaration merge key** as another row (same merge scope for declaration kinds, or overload keys for members).",
  "  - **`identical_fold`:** at least one contribution came from **identical cross-file fold**: same `name`, same `kind`, same **normalized** signature across **external** module files, folded into one row. **Row is still one `symbols` entry;** extra physical sites are listed in **`symbol_additional_files`.**",
  "  - **`overload_key`:** the row participates in **overload-style** merging (member overloads / overload rows keyed by normalized signature). Multiple overloads of the same member name may share merge mechanics or remain distinct rows depending on normalization—use **`kind_name`**, **`signature`**, and **`merge_provenance_json`** rather than assuming “one row == one overload.”",
  "  A single row can list **multiple** `kinds` when different mechanisms contributed.",
  "- **`visibility` (TEXT, optional):** JSDoc **tag-level** API visibility (`@public`, `@internal`, `@alpha`, `@beta`) when extracted—not the same thing as **`is_internal`**. A symbol may have tag **`@internal`** in docs while **`is_internal`** reflects export graph reachability; treat both columns independently.",
  "- **`is_internal` (integer 0/1):** **Package export-surface flag**, not TypeScript `private`. **`1`** means the symbol was crawled but is **not** on the public export surface from package entry resolution. **`1` does *not* mean “ignore this symbol”**—internal symbols are still valid rows and still participate in **`symbol_dependencies`** resolution.",
  "- **`is_global_augmentation`:** **`1`** if the symbol comes from **`declare global { … }`** (ambient/global augmentation). Do not confuse with ordinary exported API surface.",
  "- **`is_inherited`:** **`1`** when the row is a **synthesized inherited member** lifted from a base type (inheritance flattening), where relevant.",
  "- **`is_type_only`**, **`symbol_space`:** distinguish type-only declarations vs value namespace (`type` vs `value`).",
  "- **`re_exported_from`, deprecation fields, since-tag columns:** metadata per schema; see **`sql --schema`**.",
  "",
  "**Table `symbol_additional_files`:** (`symbol_id`, `file_path`) — **additional** package-relative declaration files that contributed to **this** merged/folded symbol row. Non-empty means “more than one physical declaration site”; combine with **`merge_provenance_json`** and **`signature`** to interpret provenance.",
  "",
  '**Table `symbol_dependencies`:** (`from_symbol_id`, `to_symbol_id_text`) — **resolved dependency edges** after graph resolution: “from symbol **uses** target symbol id (string).” Resolution follows policy **`nci-dep-v1`** (strongest first): explicit module specifier → same file → import alias in file → files reachable via **`/// <reference path="…" />`** closure → weakest: package-wide bare-name fallback (can tie homonyms—documented limitation). **`is_internal` does not block an edge.**',
  "",
  "**Table `symbol_surface_dependencies`:** same id shape as above but semantics are **namespace/module surface rollup**—aggregated dependencies for container symbols—not a substitute for **`symbol_dependencies`** on an arbitrary member row. Use **`symbol_dependencies`** when following “what does this declaration reference”; use surface rollup only when you intentionally care about the rolled-up namespace view.",
  "",
  "**Table `symbol_inherited_from_sources`:** (`symbol_id`, `source_symbol_id_text`) — for **synthesized inherited members** (`is_inherited = 1`), lists **which base/source symbol ids** contributed to this member’s flattening. Join `symbol_id` to `symbols.symbol_id` for the inherited row; **`source_symbol_id_text`** matches **`symbols.id`** strings of parents/interfaces bases. Use this when tracing **why** an inherited member exists; use **`symbol_dependencies`** for ordinary type/value references on non-inherited symbols.",
  "",
  "**Table `symbol_heritage`:** (`symbol_id`, `heritage`) — verbatim **`extends` / `implements`** clause fragments for human-readable provenance; **do not** treat `heritage` text as the machine edge set—prefer **`symbol_dependencies`** for resolved targets.",
  "",
  "**Tables `symbol_modifiers`, `symbol_decorators`:** structured modifiers and decorators attached to a symbol row—see **`sql --schema`**.",
  "",
  "**Table `package_dependencies`:** declared npm dependency names per indexed package—package-level, not symbol edges.",
  "",
  "**FTS `symbols_fts`:** full-text search over symbol name/signature/js_doc; **`query`** may use this indirectly—relational joins usually start from **`symbols`** / **`packages`**.",
  "",
  "---",
  "",
  "**Overload and merge (how to avoid wrong conclusions):**",
  "- **Merge** reduces many declaration AST nodes to **one `symbols` row** when keys collide (same merge scope for declaration kinds, or overload keys for members). **Identical fold** merges **different files** when name/kind/normalized-signature match. Always check **`merge_provenance_json`** and **`symbol_additional_files`** before assuming a single file or a single overload site.",
  '- **Overloads:** Multiple overload signatures may appear as **one fused `signature`** string when merged, or as **separate `symbols` rows** when keys stay distinct. Counting rows named `v7` without reading **`kind_name`** and **`signature`** can mis-count overloads vs re-exports vs merged overload blocks. **Separate overload rows** often share a base name and differ by **`#n`** in **`id`** when the engine needed distinct rows—pair **`id`** with **`signature`** and **`merge_provenance_json`** to interpret them. **`query overloads "<symbols.id>"`** returns the full sibling set in one call (identity is **same `package_id` + `name` + `parent_symbol_id`**, including the input row), so you do not need to enumerate **`#n`** suffixes by hand.',
  "- **`[]` from `nci sql --format json`:** output is a **JSON array** of row objects. **`[]`** means **no rows matched** your WHERE/JOIN—adjust filters (e.g. wrong `package_id`, wrong `name`, typo in path). It does **not** mean “NCI has no types.” Join **`packages`** first when selecting by package name/version.",
].join("\n");

export function buildNciFirstAgentPrimer(): string {
  return NCI_FIRST_AGENT_PRIMER_LIVE;
}

/** Reference documentation body (full table guide); written to markdown by the sync script. */
export function buildNciFirstAgentPrimerReferenceDoc(): string {
  return NCI_FIRST_AGENT_PRIMER_REFERENCE_DOC;
}

export function buildNciFirstAgentPrimerCompact(): string {
  return NCI_FIRST_AGENT_PRIMER_COMPACT;
}
