/**
 * Shared NCI-first agent primer.
 *
 * - `buildNciFirstAgentPrimerCompact()` returns the compact prompt body (used by benchmarks and the `nci-mcp` server).
 * - `buildNciFirstAgentPrimerReferenceDoc()` returns the longer SQLite/table reference used as a doc resource.
 *
 * The docs site syncs the reference doc to `apps/docs/nci-first-agent-primer.md` via
 * `pnpm --filter docs run sync:nci-first-agent-primer`.
 */

const NCI_FIRST_AGENT_PRIMER_COMPACT = [
  "You have access to the NCI CLI, which indexes TypeScript declarations from node_modules into SQLite for symbol discovery and relational joins — not a full typechecker.",
  'Subcommands: **query** (search/list) and **sql** (read-only SELECT). On Windows PowerShell use the call operator: **& "<path-to-nci.exe>" <subcommand> …args…**. **--max-rows** applies only to **nci sql** (MCP defaults a cap when invoking `nci_sql`). For **query find** and **query evidence** cap hits with **-n / --limit** (defaults: 20 and 10).',
  "## Fast path\n\nRun these calls first, in order:",
  "1. **query active-package <packageName>** — required; no substitute. Resolves **package_version**, **indexed**, and **packageManager**. On JSON, read **`meta.activePackageResolution`** (`directInstallPath` vs `fullScanFallback`) and pin **package_version** in every follow-up call.",
  "2. **query evidence** — one bundled call when you want symbol rows plus cite-ready signatures. Choose anchors by task shape:",
  "   - **Exact API names** → `--symbol <Name>` (repeatable).",
  '   - **Architectural / vague / multi-concept questions** → `--phrase "<terms>"` (repeatable FTS; runs alongside `--symbol`, not only as a fallback).',
  '   - **Both** when useful → `--symbol Output --phrase "middleware lifecycle"`.',
  "   Base: `--package <IndexedPackage> --package-version <V> [--source-package <NpmPackage>] [-n <N>] [--snippet-limit <M>]`.",
  "Response shape: **data.symbols** (deduped hits) and **data.snippets** keyed by **symbols.id** (full **signature** / **js_doc**). When **data.snippets** already answers the task, stop.",
  "**Query JSON (`--format json`):** every successful **`query …`** includes **`meta.durationMs`**, **`meta.cost`** (`light` | `moderate` | `heavy`), limits/truncation fields, and sometimes **`meta.suggestions`** (lighter commands to try when a call was slow and low-yield). If **evidence** succeeded with useful **data.snippets**, ignore suggestions and cite from there.",
  '**-n / --limit** (default 10) caps hit rows in **data.symbols**. **--snippet-limit** caps how many of those rows get a snippet in **data.snippets** (defaults to **--limit**). Use **query snippet "<id>"** as a standalone call when you need a snippet outside an evidence result.',
  "**--public-only** restricts **data.symbols** to rows where **symbols.is_internal = 0** (reachable on the package export surface). This is not the JSDoc **@public**/**@internal** tag, which lives in **symbols.visibility**.",
  "Accepted flags — only these, anything else exits non-zero: **--package** (required), **--package-version**, **--source-package**, **--symbol** (repeatable), **--phrase** (repeatable), **--kind** (case-sensitive AST kind_name: **InterfaceDeclaration**, **TypeAliasDeclaration**, **FunctionDeclaration**, **VariableStatement**, **MethodSignature**, **ExportDeclaration** — note **declare const …** rows are **VariableStatement** not **TypeAliasDeclaration**), **--public-only**, **-n / --limit**, **--snippet-limit**, **--database**, **--format** (plain|json|jsonl).",
  "**--kind** applies to every anchor in the call. Omit it if you are not certain every anchor shares the same **kind_name** — passing the wrong kind will return `0 hit(s); filter by **kindName** on the returned rows instead.",
  'Truncation: when the last element of **data.symbols** has **id**, **name**, and **kindName** all equal to **"<truncated>"**, raise **-n** or narrow with **--package-version** / **--source-package** / **--kind**. On **`--format json`**, also read **`meta.truncated`** (and related caps) on every successful **`query`** response — same facts, structured.',
  "When **data.symbols** and **data.snippets** already contain what you need, stop. Do not probe further with **read_file**, **grep**, **glob**, or **sql**.",
  "## Tool choice\n\n| Need | Prefer |\n| --- | --- |\n| Installed version + indexed check | **active-package** (required) |\n| Symbols + signatures in one call | **evidence** (`heavy`; check **meta.durationMs**) |\n| Exact name, ids only | **symbol** |\n| Cite-ready text for a known **symbols.id** | **snippet** |\n| Discovery without snippet batch load | **find** |\n| Set-level joins after you know filters | **sql** |\n\nIf **meta.suggestions** is present, follow it instead of repeating the same heavy call.",
  "## Narrowing tools\n\nUse when the fast path was insufficient:",
  "1. **query symbol <Name> --package <IndexedPackage> [--package-version] [--source-package <NpmPackage>] -n 10** — add **--source-package** to restrict to symbols whose declaration is owned by a specific npm package (**source_package_name**). Omit it when any match under the index is sufficient.",
  "2. **query find <phrase> --package <Indexed> [--source-package] [--kind <KindName>] [--package-version] -n 10** — scoped full-text search. If a dotted name returns nothing, retry with tokenized terms (Foo bar style).",
  "3. **query source-packages <IndexedPackage> <packageVersion>** — lists which source packages contribute declaration files under this index.",
  '4. **query show "<symbols.id>"** returns full row metadata including a trimmed signature preview — use it when you need column context. **query snippet "<symbols.id>"** returns the full **signature** + **js_doc** text — use it when you need cite-ready declaration text. Both take exactly one positional id. Ids suffixed **#2**, **#3**, … are separate graph rows; run **query overloads "<symbols.id>"** to get the full sibling set, then **snippet** each one.',
  "5. Path resolution — three layers: (1) which install wins (**package_dir** from active-package), (2) which package owns the declaration (**source_package_name**), (3) which file inside that install (**source_file_path**). Use **source_file_path** for disk navigation, not **file_path** when it contains index encoding. If **source_file_path** + install layout does not resolve to a real file, use **query snippet** / **query show** instead. Scope **glob**/**grep**/**read_file** only under one resolved concrete directory.",
  "6. After resolving a declaration directory, use actual filenames first. Fall back to **.d.mts** / **.d.ts** / **.d.cts** only on a miss.",
  "7. Use **read_file** / search only when **query show** / **query snippet** still lack what you need.",
  "8. A single well-scoped **SELECT** is appropriate for set-level work (name collisions, merge rows, dependency fan-out) when you already know the join and filters. Use **sql --schema** to inspect table structure first if unsure.",
  "9. Do not run **tsc -e** unless the task explicitly requires compile proof.",
  "## SQL anchor-sweep template",
  "",
  "```bash",
  "nci sql --format json --max-rows 40 -c \"SELECT s.id, s.name, s.kind_name, s.file_path, s.source_package_name FROM symbols s JOIN packages p ON p.package_id = s.package_id WHERE p.name = '<IndexedPackageName>' AND p.version = '<IndexedPackageVersion>' AND (LOWER(s.name) IN (<lowered_anchor_list>) OR s.name LIKE '%<OneAnchor>%') ORDER BY s.name LIMIT 40\"",
  "```",
  "",
  "## Path encoding\n\n**file_path** with **__nci_external__** / **__up__** are index keys, not disk paths. Join as stored; for disk use **source_package_name** + **source_file_path**, else **query snippet** / **query show**.",
  "",
  "## Graph semantics\n\nJoin **symbols** to **packages** via **package_id**. **symbols.id** → **query snippet**; **symbol_dependencies.to_symbol_id_text** → target (indexed id or stub).",
  '**symbol_dependencies** = resolved "uses". **symbol_surface_dependencies** = namespace rollup only — not interchangeable on member rows.',
  "**Stubs (no `symbols` row, no `query snippet`):** **`npm::<specifier>::<member>`** when package is in **`dependency_stub_packages`** or **`nci index -s`** (consumer imports stubbed; indexing that package itself is self-exempt). **`node::NodeJS::…`** / **`node::<builtin>::…`** for ambient Node. Follow via SQL/edges; cite from indexed ids only.",
  "**parent_symbol_id** is immediate lexical containment. **enclosing_module_declaration_id** is the surrounding ModuleDeclaration / namespace block — not a type-use edge and not always the same as **parent_symbol_id**.",
  "Id suffixes **#2**, **#3**, … disambiguate homonyms — compare the full **id**, not just **name**.",
  "**file_path** is the primary declaration site. **symbol_additional_files** lists other declaration files merged into the same symbol row.",
  "**entry_visibility_json** lists package-relative entry/barrel paths through which this symbol is reachable on the public export surface — distinct from **file_path** (the definition site) and **symbol_additional_files** (merge sites).",
  "**merge_provenance_json** describes how a row was merged: **merge_scope** (same merge-key collision), **identical_fold** (same name/kind/signature across external files), or **overload_key**. Pair with **signature** and **kind_name** when distinguishing overloads from re-exports.",
  "**is_internal = 1** means the symbol is not on the public export path from package entries. **is_inherited** means the member is synthesized via inheritance; see **symbol_inherited_from_sources** for the contributing base symbol ids.",
  "Run **sql --schema** for the full DDL.",
].join("\n\n");

/** SQLite schema reference (tables/columns). Workflow lives in the compact agent primer. */
const NCI_FIRST_AGENT_PRIMER_REFERENCE_DOC = [
  "# NCI SQLite reference",
  "",
  "CLI workflow, fast path, and tool choice are in the **agent primer** (`nci://primer/agent` / compact skill **PRIMER.md**). This document covers **schema and column semantics** for `nci sql` and MCP `nci://primer/reference`.",
  "",
  "Run **`nci sql --schema`** for authoritative DDL. If anything below disagrees with that output, **believe the schema**.",
  "",
  "## Package-relative path encoding",
  "",
  "When a declaration resolves **outside** the indexed package root, stored paths do **not** use raw `../` segments. The index uses a **canonical encoding**: each parent hop outside the package root adds **`__nci_external__`** plus one **`__up__`** segment (repeat for multiple hops). Example shape: `__nci_external__/__up__/other/x.d.ts`. That encoded string is for **stable SQLite keys and joins**, not a literal directory tree to walk under `node_modules`. **`symbols.file_path`** and symbol **`id`** strings (`pkg@version::file_path::name`) may contain these tokens. For ownership, use **`source_package_name`** + **`source_file_path`** (and `source_package_version` when non-null), not reverse-parsed `../` paths or `id` split on `::` alone.",
  "",
  "## Table `packages`",
  "",
  "`package_id`, `name`, `version`, index stats, timestamps. To filter symbols by package, use `symbols.package_id = packages.package_id` and `packages.name` / `packages.version`.",
  "",
  "## Table `symbols`",
  "",
  "One row per **graph symbol** after the merge phase:",
  "- **`symbol_id`:** integer row id.",
  "- **`package_id`:** which package this symbol belongs to.",
  "- **`id`:** stable string id (scoped to the indexed package version). Use this when joining to dependency tables or comparing to `to_symbol_id_text`.",
  "  - **`#` suffixes (`#2`, `#3`, …):** **Disambiguation**, not overload indices by themselves. The graph assigns **unique** ids when the same human-readable name would otherwise collide:",
  "    - **Exported symbols (`is_internal = 0`):** the **first** row for a given short `name` in the package typically uses `pkg@version::name`. **Further homonyms** (same exported `name`, different declarations) become `pkg@version::name#2`, `#3`, … in stable crawl order.",
  "    - **Internal symbols (`is_internal = 1`):** ids are usually **`pkg@version::file_path::name`**. If the **same file + same name** still produces multiple distinct symbols (e.g. overload rows that stay separate), the **second and later** occurrences add **`#2`, `#3`** on that **file-qualified** base (`…::file.d.ts::sym#2`).",
  "  - **If two SQL rows share the same base name but different `#n`:** they are **different symbol rows** by construction—compare full **`id`** strings, not only `name`. Do **not** assume `#2` always means “second overload” globally; it means “second disambiguated occurrence” in that package/file context.",
  "- **`name`:** the symbol’s short name; nested members may still use dotted segments in `name`—**do not infer the lexical parent only from string parsing** when `parent_symbol_id` is set.",
  "- **`kind`:** numeric internal code; **`kind_name`:** string form of the declaration kind (e.g. `FunctionDeclaration`, `InterfaceDeclaration`, `MethodSignature`, `ExportDeclaration`). Use `kind_name` with `name` and `signature` to tell functions from types from re-exports.",
  "- **`file_path`:** path to the **primary declaration site** for this graph row—package-relative. Merge may fold other sites into the same row; those extra physical files are recorded in **`symbol_additional_files`**, not by repeating them as extra `file_path` columns.",
  "- **`source_package_name`:** npm package that owns the declaration (`packages.name` for in-tree symbols; dependency package id parsed from the first `node_modules/<pkg>/` segment for `__nci_external__` paths). This is the canonical field for `--source-package` filters.",
  "- **`source_package_version`:** semver of the source package **only** when the source package is the indexed package. For external dependency declarations this is usually **NULL** by design; folder names like `@scope+pkg@x.y.z` are install-layout artifacts and are not treated as authoritative source semver.",
  "- **`source_file_path`:** path relative to `source_package_name` (mirrors `file_path` for in-package symbols; dependency-local path for external symbols). DDL stores it **NOT NULL**; use this when citing where the declaration lives inside the owning package.",
  "- **`entry_visibility_json` (TEXT, optional):** JSON array text of package-relative paths—**which package entry / barrel files make this symbol reachable on the public export surface** (`types` / `exports` roots and re-export traversal). This is the persisted SQL form of entry-surface visibility metadata. Populated when the symbol’s file (or the file resolved from package entry re-export) is one of the indexed **entry files**. **Not** the same as **`file_path`**: a symbol may be **defined** in `dist/foo.d.ts` but **reachable** only via `dist/index.d.ts`—then `file_path` is `foo`, while **`entry_visibility_json`** lists index/barrel paths that surface it. **Not** the same as **`symbol_additional_files`**: those are **extra declaration merge sites** for the same merged symbol, not “which entry re-exported this name.” If the only entry path equals **`file_path`** alone, the engine often omits the field as redundant—**NULL / absent** does not mean “not exported”; use **`is_internal`** plus this column when present.",
  "- **`signature`:** declaration signature / export text. **After merge,** the engine may **fuse** several normalized-distinct signature bodies into one field (newline-separated blocks), not “first file only.” If two overloads collapse when their normalized signatures match, you will not see duplicate raw text for the same normalized overload key.",
  "- **`js_doc`:** JSDoc when present.",
  "- **`parent_symbol_id`:** the **lexical / containment** parent for member shapes (e.g. a method’s parent class or interface id). This answers “this member lives under which container in the graph.” It is **not** a “this type uses that type” edge. For **use** relationships, use **`symbol_dependencies`** (or the graph’s `dependencies` when not using SQL). **Never** replace dependency reasoning with `parent_symbol_id` or vice versa.",
  "- **`enclosing_module_declaration_id`:** string id of the **enclosing module / namespace declaration** row (`ModuleDeclaration`-like container) for module-scoped symbols—**which module block** this symbol belongs to. **Not** a type-reference edge and **not** the same as `parent_symbol_id` for every kind (parent is often the immediate lexical owner; enclosing module is the surrounding module/namespace declaration id). Use it when you need “inside which module namespace” vs following **`symbol_dependencies`** for references.",
  "- **`merge_provenance_json`:** present when this row **absorbed more than one** declaration. JSON object; typically a `kinds` array whose values describe **how** the row was formed (snake_case labels), for example:",
  "  - **`merge_scope`:** at least one contribution came from the same **declaration merge key** as another row (same merge scope for declaration kinds, or overload keys for members).",
  "  - **`identical_fold`:** at least one contribution came from **identical cross-file fold**: same `name`, same `kind`, same **normalized** signature across **external** module files, folded into one row. **Row is still one `symbols` entry;** extra physical sites are listed in **`symbol_additional_files`.**",
  "  - **`overload_key`:** the row participates in **overload-style** merging (member overloads / overload rows keyed by normalized signature). Multiple overloads of the same member name may share merge mechanics or remain distinct rows depending on normalization—use **`kind_name`**, **`signature`**, and **`merge_provenance_json`** rather than assuming “one row == one overload.”",
  "  A single row can list **multiple** `kinds` when different mechanisms contributed.",
  "- **`visibility` (TEXT, optional):** JSDoc **tag-level** API visibility (`@public`, `@internal`, `@alpha`, `@beta`) when extracted—not the same thing as **`is_internal`**. A symbol may have tag **`@internal`** in docs while **`is_internal`** reflects export graph reachability; treat both columns independently.",
  "- **`is_internal` (integer 0/1):** **Package export-surface flag**, not TypeScript `private`. **`1`** means the symbol was crawled but is **not** on the public export surface from package entry resolution. **`1` does *not* mean “ignore this symbol”**—internal symbols are still valid rows and still participate in **`symbol_dependencies`** resolution.",
  "- **`is_global_augmentation`:** **`1`** if the symbol comes from **`declare global { … }`** (ambient/global augmentation). Do not confuse with ordinary exported API surface.",
  "- **`is_inherited`:** **`1`** when the row is a **synthesized inherited member** lifted from a base type (inheritance flattening), where relevant.",
  "- **`is_type_only`**, **`symbol_space`:** distinguish type-only declarations vs value namespace (`type` vs `value`).",
  "- **`re_exported_from`, deprecation fields, since-tag columns:** metadata per schema; see **`sql --schema`**.",
  "",
  "## Table `symbol_additional_files`",
  "",
  "(`symbol_id`, `file_path`) — **additional** package-relative declaration files that contributed to **this** merged/folded symbol row. Non-empty means “more than one physical declaration site”; combine with **`merge_provenance_json`** and **`signature`** to interpret provenance.",
  "",
  "## Table `symbol_dependencies`",
  "",
  '(`from_symbol_id`, `to_symbol_id_text`) — resolved "uses". **`to_symbol_id_text`**: **`symbols.id`**, or stub **`npm::<specifier>::<member>`** (`dependency_stub_packages` / `nci index -s`), **`node::NodeJS::…`**, **`node::<builtin>::…`**, **`protocol::…`** (no `symbols` row). Resolution order: module specifier → same file → import alias → `/// <reference … />` closure → bare-name fallback. **`is_internal` does not block an edge.**',
  "",
  "## Table `symbol_surface_dependencies`",
  "",
  "Same id shape as above but semantics are **namespace/module surface rollup**—aggregated dependencies for container symbols—not a substitute for **`symbol_dependencies`** on an arbitrary member row. Use **`symbol_dependencies`** when following “what does this declaration reference”; use surface rollup only when you intentionally care about the rolled-up namespace view.",
  "",
  "## Table `symbol_inherited_from_sources`",
  "",
  "(`symbol_id`, `source_symbol_id_text`) — for **synthesized inherited members** (`is_inherited = 1`), lists **which base/source symbol ids** contributed to this member’s flattening. Join `symbol_id` to `symbols.symbol_id` for the inherited row; **`source_symbol_id_text`** matches **`symbols.id`** strings of parents/interfaces bases. Use this when tracing **why** an inherited member exists; use **`symbol_dependencies`** for ordinary type/value references on non-inherited symbols.",
  "",
  "## Table `symbol_heritage`",
  "",
  "(`symbol_id`, `heritage`) — verbatim **`extends` / `implements`** clause fragments for human-readable provenance; **do not** treat `heritage` text as the machine edge set—prefer **`symbol_dependencies`** for resolved targets.",
  "",
  "## Tables `symbol_modifiers`, `symbol_decorators`",
  "",
  "Structured modifiers and decorators attached to a symbol row—see **`sql --schema`**.",
  "",
  "## Table `package_dependencies`",
  "",
  "Declared npm dependency names per indexed package—package-level, not symbol edges.",
  "",
  "## FTS `symbols_fts`",
  "",
  "Full-text search over symbol name/signature/js_doc; **`query`** may use this indirectly—relational joins usually start from **`symbols`** / **`packages`**.",
  "",
  "---",
  "",
  "## Overload and merge",
  "",
  "How to avoid wrong conclusions:",
  "- **Merge** reduces many declaration AST nodes to **one `symbols` row** when keys collide (same merge scope for declaration kinds, or overload keys for members). **Identical fold** merges **different files** when name/kind/normalized-signature match. Always check **`merge_provenance_json`** and **`symbol_additional_files`** before assuming a single file or a single overload site.",
  '- **Overloads:** Multiple overload signatures may appear as **one fused `signature`** string when merged, or as **separate `symbols` rows** when keys stay distinct. Counting rows by **`name`** alone without **`kind_name`** and **`signature`** mis-counts overloads vs re-exports. Rows that share a base name may differ by **`#n`** in **`id`**—pair **`id`**, **`signature`**, and **`merge_provenance_json`**. CLI **`query overloads "<symbols.id>"`** returns the full sibling set (**same `package_id` + `name` + `parent_symbol_id`**, including the input row).',
  "- **`[]` from `nci sql --format json`:** output is a **JSON array** of row objects. **`[]`** means **no rows matched** your WHERE/JOIN—adjust filters (e.g. wrong `package_id`, wrong `name`, typo in path). It does **not** mean the index is empty. Join **`packages`** first when filtering by package name/version.",
].join("\n");

/** Reference documentation body (full table guide); written to markdown by the sync script. */
export function buildNciFirstAgentPrimerReferenceDoc(): string {
  return NCI_FIRST_AGENT_PRIMER_REFERENCE_DOC;
}

export function buildNciFirstAgentPrimerCompact(): string {
  return NCI_FIRST_AGENT_PRIMER_COMPACT;
}
