/// NCI Engine — Snapshot Tests (TS Oracle Comparison)
///
/// Runs the Rust pipeline on fixture packages and compares
/// the output against golden JSON files generated by the
/// TypeScript reference implementation.
///
/// ## Workflow
/// 1. Generate golden files:
///    `cd packages/nci-core && npx tsx scripts/generate-snapshots.ts`
/// 2. Run these tests:
///    `cargo test --test snapshot_tests`
/// 3. If insta reports new `*.snap.new` files under `tests/snapshots/`, accept them with
///    `cargo insta accept --manifest-path packages/nci-engine/Cargo.toml --include-ignored`
///    (that directory is gitignored, so insta needs `--include-ignored`).
///
/// Any mismatch indicates a behavioral difference between the
/// Rust and TypeScript implementations.
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use nci_engine::graph::build_package_graph;
use nci_engine::resolver::normalize_path;
use nci_engine::types::{PackageGraph, PackageInfo, SharedString};

fn fixtures_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("packages")
        .join("nci-core")
        .join("fixtures")
}

fn oracle_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("snapshots")
        .join("oracle")
}

fn normalise_graph(graph: &mut PackageGraph, fixture_dir: &Path) {
    graph.crawl_duration_ms = 0.0;
    graph.build_duration_ms = 0.0;

    let fixture_dir_str = fixture_dir.to_string_lossy().replace('\\', "/");

    for symbol in &mut graph.symbols {
        let abs = symbol.file_path.replace('\\', "/");
        if abs.starts_with(&fixture_dir_str) {
            let rest = &abs[fixture_dir_str.len()..];
            symbol.file_path = rest.strip_prefix('/').unwrap_or(rest).to_string().into();
        }

        if let Some(files) = symbol.additional_files.as_ref() {
            let mut new_files = Vec::new();
            for file in files.iter() {
                let abs = file.replace('\\', "/");
                if abs.starts_with(&fixture_dir_str) {
                    let rest = &abs[fixture_dir_str.len()..];
                    new_files.push(SharedString::from(
                        rest.strip_prefix('/').unwrap_or(rest).to_string(),
                    ));
                } else {
                    new_files.push(file.clone());
                }
            }
            symbol.additional_files = Some(new_files.into());
        }

        let mut sorted_deps = symbol.dependencies.to_vec();
        sorted_deps.sort();
        symbol.dependencies = sorted_deps.into();
    }

    graph
        .symbols
        .sort_by(|left, right| left.name.cmp(&right.name));
}

fn build_fixture_graph(fixture_name: &str) -> PackageGraph {
    let fixture_dir = fixtures_dir().join(fixture_name);
    let pkg_json_path = fixture_dir.join("package.json");

    let (name, version) = if pkg_json_path.exists() {
        let raw = fs::read_to_string(&pkg_json_path).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&raw).unwrap();
        (
            parsed["name"].as_str().unwrap_or(fixture_name).to_string(),
            parsed["version"].as_str().unwrap_or("1.0.0").to_string(),
        )
    } else {
        (fixture_name.to_string(), "1.0.0".to_string())
    };

    let info = PackageInfo {
        is_scoped: name.starts_with('@'),
        name: name.into(),
        version: version.into(),
        dir: normalize_path(&fixture_dir),
    };

    let mut graph = build_package_graph(&info, None);
    normalise_graph(&mut graph, &fixture_dir);
    graph
}

fn load_oracle(fixture_name: &str) -> Option<serde_json::Value> {
    let oracle_path = oracle_dir().join(format!("{fixture_name}.json"));
    if !oracle_path.exists() {
        return None;
    }
    let raw = fs::read_to_string(&oracle_path).unwrap();
    Some(serde_json::from_str(&raw).unwrap())
}

fn normalise_oracle(oracle: &mut serde_json::Value) {
    if let Some(symbols) = oracle
        .get_mut("symbols")
        .and_then(|symbols_node| symbols_node.as_array_mut())
    {
        for sym in symbols.iter_mut() {
            if let Some(deps) = sym
                .get_mut("dependencies")
                .and_then(|deps_node| deps_node.as_array_mut())
            {
                deps.sort_by(|left, right| {
                    left.as_str()
                        .unwrap_or("")
                        .cmp(&right.as_str().unwrap_or(""))
                });
            }
            if let Some(obj) = sym.as_object_mut() {
                obj.remove("rawDependencies");
            }
        }
        symbols.sort_by(|left_sym, right_sym| {
            let left_name = left_sym
                .get("name")
                .and_then(|name_val| name_val.as_str())
                .unwrap_or("");
            let right_name = right_sym
                .get("name")
                .and_then(|name_val| name_val.as_str())
                .unwrap_or("");
            left_name.cmp(right_name)
        });
    }
}

fn compare_symbol_names_and_counts(
    rust_graph: &PackageGraph,
    oracle: &serde_json::Value,
    fixture_name: &str,
) {
    let oracle_symbols = oracle
        .get("symbols")
        .and_then(|symbols_val| symbols_val.as_array())
        .unwrap();

    let mut rust_names: Vec<&str> = rust_graph
        .symbols
        .iter()
        .map(|rust_symbol| rust_symbol.name.as_ref())
        .collect();
    rust_names.sort();

    let mut ts_names: Vec<String> = oracle_symbols
        .iter()
        .filter_map(|oracle_entry| {
            oracle_entry
                .get("name")
                .and_then(|name_val| name_val.as_str())
                .map(String::from)
        })
        .collect();
    ts_names.sort();

    assert_eq!(
        rust_graph.symbols.len(),
        oracle_symbols.len(),
        "[{fixture_name}] Symbol count mismatch: Rust={}, TS={}",
        rust_graph.symbols.len(),
        oracle_symbols.len()
    );

    assert_eq!(
        rust_names, ts_names,
        "[{fixture_name}] Symbol names mismatch"
    );
}

fn compare_structural_properties(
    rust_graph: &PackageGraph,
    oracle: &serde_json::Value,
    fixture_name: &str,
) {
    let oracle_symbols = oracle
        .get("symbols")
        .and_then(|symbols_val| symbols_val.as_array())
        .unwrap();

    let oracle_by_id: HashMap<&str, &serde_json::Value> = oracle_symbols
        .iter()
        .filter_map(|oracle_symbol| {
            oracle_symbol
                .get("id")
                .and_then(|id_val| id_val.as_str())
                .map(|symbol_id| (symbol_id, oracle_symbol))
        })
        .collect();

    for rust_sym in &rust_graph.symbols {
        let ts_sym = match oracle_by_id.get::<str>(rust_sym.id.as_ref()) {
            Some(oracle_row) => *oracle_row,
            None => {
                panic!(
                    "[{fixture_name}] Symbol ID '{}' (name: {}) exists in Rust but not in TS oracle",
                    rust_sym.id, rust_sym.name
                );
            }
        };

        if let Some(ts_kind_name) = ts_sym
            .get("kindName")
            .and_then(|kind_field| kind_field.as_str())
        {
            assert_eq!(
                rust_sym.kind_name.as_ref(),
                ts_kind_name,
                "[{fixture_name}] Kind mismatch for '{}' ({})",
                rust_sym.name,
                rust_sym.id
            );
        }

        if let Some(ts_file_path) = ts_sym
            .get("filePath")
            .and_then(|path_field| path_field.as_str())
        {
            assert_eq!(
                rust_sym.file_path.as_ref(),
                ts_file_path,
                "[{fixture_name}] File path mismatch for '{}'",
                rust_sym.name
            );
        }

        if let Some(ts_type_only) = ts_sym.get("isTypeOnly").and_then(|flag| flag.as_bool()) {
            assert_eq!(
                rust_sym.is_type_only, ts_type_only,
                "[{fixture_name}] isTypeOnly mismatch for '{}'",
                rust_sym.name
            );
        }

        if let Some(ts_space) = ts_sym
            .get("symbolSpace")
            .and_then(|space_field| space_field.as_str())
        {
            let rust_space = match rust_sym.symbol_space {
                nci_engine::types::SymbolSpace::Type => "type",
                nci_engine::types::SymbolSpace::Value => "value",
            };
            assert_eq!(
                rust_space, ts_space,
                "[{fixture_name}] symbolSpace mismatch for '{}'",
                rust_sym.name
            );
        }

        if let Some(ts_heritage) = ts_sym
            .get("heritage")
            .and_then(|heritage_field| heritage_field.as_array())
        {
            let ts_heritage_strs: Vec<&str> = ts_heritage
                .iter()
                .filter_map(|heritage_item| heritage_item.as_str())
                .collect();
            assert_eq!(
                rust_sym
                    .heritage
                    .iter()
                    .map(|name| name.as_ref())
                    .collect::<Vec<_>>(),
                ts_heritage_strs,
                "[{fixture_name}] Heritage mismatch for '{}'",
                rust_sym.name
            );
        }

        if let Some(ts_deps) = ts_sym
            .get("dependencies")
            .and_then(|deps_field| deps_field.as_array())
        {
            assert_eq!(
                rust_sym.dependencies.len(),
                ts_deps.len(),
                "[{fixture_name}] Dependency count mismatch for '{}'",
                rust_sym.name
            );
        }

        let ts_visibility = ts_sym
            .get("visibility")
            .and_then(|vis_field| vis_field.as_str());
        let rust_visibility = rust_sym
            .visibility
            .as_ref()
            .map(|visibility| match visibility {
                nci_engine::types::Visibility::Public => "public",
                nci_engine::types::Visibility::Internal => "internal",
                nci_engine::types::Visibility::Alpha => "alpha",
                nci_engine::types::Visibility::Beta => "beta",
            });
        assert_eq!(
            rust_visibility, ts_visibility,
            "[{fixture_name}] Visibility mismatch for '{}'",
            rust_sym.name
        );
    }
}

macro_rules! snapshot_test {
    ($test_name:ident, $fixture_name:expr) => {
        #[test]
        fn $test_name() {
            let fixture_name = $fixture_name;
            let rust_graph = build_fixture_graph(fixture_name);

            insta::assert_json_snapshot!(format!("rust_{}", fixture_name), &rust_graph);

            if let Some(mut oracle) = load_oracle(fixture_name) {
                normalise_oracle(&mut oracle);
                compare_symbol_names_and_counts(&rust_graph, &oracle, fixture_name);
                compare_structural_properties(&rust_graph, &oracle, fixture_name);
            }
        }
    };
}

snapshot_test!(snapshot_simple_export, "simple-export");
snapshot_test!(snapshot_re_export_chain, "re-export-chain");
snapshot_test!(snapshot_namespace_cases, "namespace-cases");
snapshot_test!(snapshot_class_instance, "class-instance");
snapshot_test!(
    snapshot_inherited_member_flattening,
    "inherited-member-flattening"
);
snapshot_test!(snapshot_deprecated_exports, "deprecated-exports");
snapshot_test!(snapshot_visibility_tags, "visibility-tags");
snapshot_test!(snapshot_enum_declaration, "all-export-forms");
snapshot_test!(snapshot_circular_deps, "circular-deps");
snapshot_test!(snapshot_deep_chain, "deep-chain");
snapshot_test!(snapshot_wildcard_reexport, "wildcard-reexport");
snapshot_test!(snapshot_triple_slash_refs, "triple-slash-refs");
snapshot_test!(
    snapshot_triple_slash_after_block_comment,
    "triple-slash-after-block-comment"
);
snapshot_test!(snapshot_parser_edge_case, "parser-edge-case");
snapshot_test!(snapshot_computed_properties, "computed-properties");
snapshot_test!(snapshot_literal_export, "literal-export");
snapshot_test!(snapshot_type_alias, "since-decl");
snapshot_test!(snapshot_conditional_exports, "conditional-exports");
snapshot_test!(snapshot_subpath_exports, "subpath-exports");
snapshot_test!(snapshot_types_versions, "types-versions");
snapshot_test!(snapshot_no_types_pkg, "no-types-pkg");
snapshot_test!(snapshot_string_exports, "string-exports");
snapshot_test!(snapshot_namespace_reexport, "namespace-reexport");
snapshot_test!(snapshot_multi_star_exports, "multi-star-exports");
snapshot_test!(snapshot_local_reexport, "local-reexport");
snapshot_test!(snapshot_local_export, "local-export");
snapshot_test!(snapshot_nested_prefix, "nested-prefix");
snapshot_test!(snapshot_import_cases, "import-cases");
snapshot_test!(snapshot_merged_symbols, "merged-symbols");
snapshot_test!(snapshot_name_collision, "name-collision");
snapshot_test!(snapshot_deps_pkg, "deps-pkg");
snapshot_test!(
    snapshot_qualified_namespace_deps,
    "qualified-namespace-deps"
);
snapshot_test!(snapshot_inline_import_type, "inline-import-type");
snapshot_test!(snapshot_class_statics, "class-statics");
snapshot_test!(snapshot_global_augmentation, "global-augmentation");
snapshot_test!(snapshot_mixin_composition, "mixin-composition");
snapshot_test!(
    snapshot_module_global_augmentation_ref,
    "module-global-augmentation-ref"
);
snapshot_test!(snapshot_visibility_merge, "visibility-merge");
snapshot_test!(snapshot_since_inheritance, "since-inheritance");
snapshot_test!(
    snapshot_deep_recursion_duplicates,
    "deep-recursion-duplicates"
);
snapshot_test!(snapshot_id_stability_sort, "id-stability-sort");
snapshot_test!(
    snapshot_resolver_strict_boundary,
    "resolver-strict-boundary"
);
snapshot_test!(snapshot_traversal_depth_edge, "traversal-depth-edge");
snapshot_test!(snapshot_shared_type_pruning, "shared-type-pruning");
snapshot_test!(
    snapshot_shared_type_sibling_expansion,
    "shared-type-sibling-expansion"
);
snapshot_test!(
    snapshot_accessor_member_extraction,
    "accessor-member-extraction"
);
snapshot_test!(
    snapshot_member_property_extraction,
    "member-property-extraction"
);
snapshot_test!(snapshot_internal_overload_ref, "internal-overload-ref");
snapshot_test!(
    snapshot_merge_key_signature_parity,
    "merge-key-signature-parity"
);
snapshot_test!(
    snapshot_cross_file_overload_reexport,
    "cross-file-overload-reexport"
);
snapshot_test!(
    snapshot_namespace_name_prefix_boundary,
    "namespace-name-prefix-boundary"
);
snapshot_test!(
    snapshot_namespace_export_method_overloads,
    "namespace-export-method-overloads"
);
snapshot_test!(
    snapshot_private_class_field_skip,
    "private-class-field-skip"
);
snapshot_test!(
    snapshot_class_typeof_flat_members,
    "class-typeof-flat-members"
);
snapshot_test!(
    snapshot_typeof_import_type_query,
    "typeof-import-type-query"
);
snapshot_test!(
    snapshot_parenthesized_intersection_expansion,
    "parenthesized-intersection-expansion"
);
snapshot_test!(
    snapshot_dual_name_interface_const,
    "dual-name-interface-const"
);
snapshot_test!(
    snapshot_multi_declaration_heritage,
    "multi-declaration-heritage"
);
snapshot_test!(
    snapshot_heritage_generic_multi_extends,
    "heritage-generic-multi-extends"
);

#[test]
fn all_oracles_have_tests() {
    let oracle = oracle_dir();
    if !oracle.exists() {
        return;
    }

    let oracle_count = fs::read_dir(&oracle)
        .unwrap()
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry
                .path()
                .extension()
                .map(|ext| ext == "json")
                .unwrap_or(false)
        })
        .count();

    if oracle_count > 0 {
        eprintln!("ℹ️ Found {} oracle snapshots.", oracle_count);
    }
}
